### ISSUE TITLE
Pygmentize and python version

### ISSUE THREAD

**Issue by sagebomb** [wikimatze/hammer.vim#27]
In some linux distros (for example in my Archlinux) by default used python3, and pygmentize call python 3 by `/usr/bin/env python` . But pygmentize does not work witn python3 (?). I install python2 and create symlink to /usr/bin/python. All works. Maybe need add to README for that?

**Comment by ghost** [comment]
Hm, I'm not familiar with Python but according to the Pygments FAQ, Python3 is supported: http://pygments.org/faq/#python3

**Comment by sagebomb** [comment]
``` bash
[~]$> sudo pacman -S python
разрешение зависимостей...
проверка на взаимную несовместимость...

Цели (1): python-3.2.2-1
...
(1/1) установка python
[~]$> vim Dev/hammer.vim/README.md #and call :Hammer from Vim
Traceback (most recent call last):
  File "/usr/lib/ruby/gems/1.9.1/gems/pygmentize-0.0.3/vendor/pygmentize.py", line 3, in <module>
    import sys, pygments.cmdline
  File "/usr/lib/ruby/gems/1.9.1/gems/pygmentize-0.0.3/vendor/pygments/__init__.py", line 46
    except TypeError, err:
                    ^
SyntaxError: invalid syntax
```

**Comment by sagebomb** [comment]
``` bash
[~]$> sudo pacman -Rcnsu python #remove python3
проверка зависимостей...

Удалить (1): python-3.2.2-1

Размер удаляемых файлов:   75,30 МБ

Хотите удалить эти пакеты? [Y/n] y
(1/1) удаление python

[~]$> pacman -Q python2 #python2 installed
python2 2.7.2-2
[~]$> vim Dev/hammer.vim/README.md 
/usr/bin/env: python: Нет такого файла или каталога #no such file or directory after call :Hammer
[~]$> sudo ln -s /usr/bin/python2 /usr/bin/python
[~]$> vim Dev/hammer.vim/README.md #All works
```

**Comment by sagebomb** [comment]
``` bash
[~]$> rvm use system
Now using system ruby.
[~]$> find /usr/lib/ruby/gems/1.9.1/gems/ -name setup.py
[~]$> 
```

I think you need add this info into README, no?

**Comment by ghost** [comment]
It might be a better idea to tell people not to use that gem? :-)
It vendors 1.3.1, but locally on my computer:

```
➜  hammer git:(feature/github-flavored-markdown) pygmentize -V       
Pygments version 1.4, (c) 2006-2008 by Georg Brandl.
```

The gem hasn't been updated since May, 2011.

**Comment by sagebomb** [comment]
I not have alternative variant. Just add into readme as dependency pygmentize gem and _python2_ support for that, or build pygmenize manually for python3, if this need.

**Comment by ghost** [comment]
Sure, you're welcome to open a pull request and do that.
